### ISSUE TITLE
ofxSyphon set-up

### ISSUE THREAD

**Issue by alexec** [darrenmothersele/partyAnimal#1]
Can you let me know how to set this up?

**Comment by darrenmothersele** [comment]
https://github.com/astellato/ofxSyphon#instructions
1. put the ofxSyphon repo in the oF addons folder (remove the examples or move them to the examples folder).
2. drag the ofxSyphon folder to xcode in addons.
3. add the copy files build step to copy the Syphon framework. you'll see one already that copies GLUT. 
4. Add the location of the Syphon framework (addons/ofxSyphon/lib/Syphon/lib/osx) to the Framework Search Paths Build Setting in your Xcode project.

Did that not work?

**Comment by alexec** [comment]
No. I'm not familiar with Xcode, all this manual set-up in making me angry :(((

**Comment by darrenmothersele** [comment]
please build a package manager for openFrameworks :)

**Comment by alexec** [comment]
Ill raise a ticket!
